import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OUTFITTED",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <link rel="icon" href="public\wardrobe.ico" sizes="any" />
      <link
       rel="icon"
       href="/icon?<generated>"
       type="image/<generated>"
       sizes="<generated>"
       />
      </head>
      <body className={inter.className}>
        <Provider>
          <Header/>
          {children}
        </Provider>
        </body>
    </html>
  );
}
